swagger: '2.0'
info:
  title: YourApp
  description: 'your App'
  version: 1.0.0
host: 'localhost:5000'
basePath: /service/
consumes:
  - application/json
produces:
  - application/json

paths:
  /zones:
    get:
      tags:
        - zones
      summary: get all zones (search)
      x-swagger-router-controller: zones.search
      parameters:
        - name: q
          in: query
          required: false
          type: string
          description: search inside email and fname and lname
        - name: limit
          in: query
          required: false
          type: integer
          description: limit for page
        - name: page
          in: query
          required: false
          type: integer
          description: page


      responses:
        '200':
          description: zones list
          schema:
            $ref: '#/definitions/zone'

    put:
      tags:
        - zones
      summary: insert zone
      x-swagger-router-controller: zones.insert
      parameters:
        - name: zone
          in: body
          required: true
          schema:
            $ref: '#/definitions/zone'

      responses:
        '200':
          description: zones added
          schema:
            $ref: '#/definitions/zone'
    delete:
      tags:
        - zones
      summary: delete zone
      x-swagger-router-controller: zones.remove
      parameters:
        - name: _id
          in: query
          required: true
          type: string

      responses:
        '200':
          description: zones
          schema:
            $ref: '#/definitions/zone'
    patch:
      tags:
        - zones
      summary: patch zone
      x-swagger-router-controller: zones.update
      parameters:
        - name: zone
          in: body
          required: true
          schema:
            $ref: '#/definitions/zone'

      responses:
        '200':
          description: zones
          schema:
            $ref: '#/definitions/zone'


definitions:
  zone:
    type: object
    properties:
      description:
        type: string
      code:
        type: string
      _id:
        type: string